# -*- coding: utf-8 -*-
"""AI_EDA_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKOgCfdiDUL7aFQ2d-pM2QJjrr8eDZ3h
"""

import pandas as pd #pd is just a variable.
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_df = pd.read_csv(url)

print(titanic_df) #get the dataset

"""get the information about the dataset."""

print(titanic_df.info()) #get the details about the dataset.

"""Data profiling."""

print("missing values")
print(titanic_df.isnull().sum()) # this shows how many null values are there for each column.

"""Why are we finding null values?
if the data is empty the data isn't useful.
for example the cabin column:
total data rows: 890
null rows:687.

get a list of age
"""

print(titanic_df['Age'])

"""How to calculate the mean."""

print("MEAN") #age
print(titanic_df["Age"].mean())

"""mean for the fair"""

print(titanic_df["Fare"].mean())

"""How to calculate the midian."""

print("median") #median
print(titanic_df["Age"].median())
print("------------------------------------------")
print(titanic_df["Fare"].median())

"""Mean age is > Median age that could be because there are few older passengers.

Mean fair is < median fair. so the graph is skew to the right side.

How to calculate the mode.
"""

print("mode") #mode
print(titanic_df["Age"].mode())
print("------------------------------------------")
print(titanic_df["Fare"].mode())

"""how to find the ship has most male or female passengers."""

print("Most common embarked port: ",titanic_df['Embarked'].mode()[0])#mode
print("Most comman gender: ",titanic_df['Sex'].mode()[0])

"""Data Visualization"""

import matplotlib.pyplot as plt

print(titanic_df.Survived)

print(titanic_df.Survived.value_counts())

count = titanic_df.Survived.value_counts()
count.plot(kind='bar', alpha = .5)
plt.title('Survived')
plt.xlabel('Survived or not')
plt.ylabel(' passenger Count')
plt.show()

"""another library."""

import seaborn as sns #import lib

"""Draw the graph."""

sns.countplot(x='Sex', hue='Survived', data=titanic_df)
plt.title("survived count by gender.")
plt.xlabel("gender")
plt.ylabel("passenger count")
plt.legend(title='Survived',labels=['No','Yes'])
plt.show()

"""survived by the age group"""

print(titanic_df['Age'])

"""need to do some formatting."""

titanic_df['Age_group'] = pd.cut(titanic_df['Age'],bins=[0,12,18,40,60,80],labels=['child','teen','adult','senior','old'])
sns.countplot(x='Age_group', hue='Survived', data=titanic_df)
plt.title("survived count by age.")
plt.xlabel("Age Group")
plt.ylabel("passenger count")
plt.legend(title='Survived',labels=['No','Yes'])
plt.show()

"""Data analizing  using the class."""

sns.countplot(x='Pclass', hue='Survived', data=titanic_df)
plt.title("survived count by Class.")
plt.xlabel("passenger class(1=First class)")
plt.ylabel("passenger count")
plt.legend(title='Survived',labels=['No','Yes'])
plt.show()

"""h.w:- create a report.

*   find the public dataset or seaborn dataset
*   real world datasewt



"""

