# -*- coding: utf-8 -*-
"""AI_EDA_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwsVWJ7ZkKMLEOnu3YIjK7cTY_Gqlvic

titanic data set:
https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv

import the libraries.
"""

import pandas as pd #pd is just a variable.

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

"""define a variable."""

titanic_df = pd.read_csv(url)

print(titanic_df)

"""printing the shape"""

print("shape of the dataset ", titanic_df.shape )
print("-----------------------------------------------------------------------------------------------------------------")

print(titanic_df.head())
print("-----------------------------------------------------------------------------------------------------------------")

print(titanic_df.head(20))
print("-----------------------------------------------------------------------------------------------------------------")

print(titanic_df.dtypes)