# -*- coding: utf-8 -*-
"""python_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2zyURKCOTWauxJb5kLRteoO_4yhMSEx

import pandas is the first step and assign it to the 'pd' variable.
"""

import pandas as pd

"""create a column and see the difference."""

column = ["Mariya","Batman","Spongebob"]
#just print it to get the basic structure.
print(column)
print("----------------------------------------------------------")
#now assign it to the pandas.
data = pd.DataFrame(column)
print(data)

"""So now we try to put the colum names"""

title_column = {
    "name":["Mariya","Batman","Spongebob"]
}
data = pd.DataFrame(title_column)
print(data)

"""Adding new columns"""

title_column = {
    "name":["Mariya","Batman","Spongebob"],
    "age":[20,30,40],
    "height":[1.67,1.9,0.25],
    "weight":[50,50,50]
}
data = pd.DataFrame(title_column)
print(data)
#

"""only get values in one column"""

select_column = data["height"]
print(select_column)

"""if only need the batman height."""

select_column = data["height"][1]
print(select_column)

"""select a row"""

select_row = data.iloc[1] #in the case of batman
print(select_row)

"""if we need only the weight."""

select_row = data.iloc[1]["weight"] #in the case of batman
print(select_row)

"""manipulate dataframe values."""

bmi = [] # weight/(height ** 2)
for i in range(len(data)):
    bmi.append(data["weight"][i]/(data.iloc[i]["height"]**2))
data["bmi"] = bmi
print(data)

"""save the dataframe to a file"""

data.to_csv("bmi.csv",sep="\t") #sep is use to separate the data.
data.to_csv("bmi.txt",sep="\t") #sep is use to separate the data.

"""load them from a csv file."""

data = pd.read_csv("bmi.csv", sep="\t")
print(data)

"""remove the first column"""

data = pd.read_csv("bmi.csv",index_col = False, sep="\t")
print(data)

"""This can be connect to sql database as well but i am not going to code that here.

next

how to print only the first 2 rows.
"""

print(data.head())# to get all values
print("----------------------------------------------------------------")
print(data.head(2))#to get two rows each.

"""if we want last 2 we have to change the code into"""



print(data.tail())# to get all values
print("----------------------------------------------------------------")
print(data.tail(2))#to get two rows each.

"""filter the data"""

filter = data[data["age"] == 20]
print(filter)

"""replace data entries"""

replaced_data = data.replace("Mariya","Mariya2")
print(replaced_data)

"""remove data."""

remove_column = data.drop("bmi",axis = 1)
print(remove_column)
print("---------------------------------------------------------------")
remove_column = data.drop(["height","weight"],axis = 1)
print(remove_column)
print("---------------------------------------------------------------")
remove_row = data.iloc[0:2]
print(remove_row)
print("---------------------------------------------------------------")
print(data)

"""add new rows"""

row = {
    "name": "aag",
    "age":20,
    "height":1.23,
    "weight":100,
    "bmi":1.2356
}
new_row_df = pd.DataFrame([row])
new = pd.concat([data, new_row_df], ignore_index=True)
print(new)

"""remove duplicates"""

new = new.drop_duplicates(subset = ["name"])
print("now the row count is ",len(new))